### ISSUE TITLE
在将来会加入如下功能嘛？

### ISSUE THREAD

**Issue by xhzengAIB** [dudongdaoqi/LCGridView#1]
你好!
1、支持竖直方向上的滚动
2、现实多线程多任务显示网络图片
3、支持缓存图片

Jack

**Comment by dudongdaoqi** [comment]
可以增加！
1.已经实现了,初始化时，将参数isPageControl设置为NO即可
2.3等我空闲的时候，可以搞一下！

**Comment by xhzengAIB** [comment]
@dudongdaoqi 
好的！谢谢您的开源库，我学到了很多东西

**Comment by xhzengAIB** [comment]
@dudongdaoqi 
希望用arc去实现，因为大部分的手机已经在iOS6以及iOS7了，所以arc会比较受欢迎
